### PR TITLE
Minigun Debuff

### PR DESCRIPTION
**Pull request by Ann1h1lator**
I unintentionally made minigun too overpowered and within 24 hours somehow everyone knew it was meta, people can't keep secrets and mini will break the game if it's this strong and everyone's using it

### CODE REVIEW

**Comment by DamienVesper** [comment]
This is why we don't mess with numbers without tests.

**Comment by Ann1h1lator** [comment]
Actually no, I did calculate that it would do 7% more damage per second than spreadshot. But it looks alot more like 20 or 30% in game for some reason

**Comment by Ann1h1lator** [comment]
There's obviously no way it was really 7% because a generator would have a bigger difference (8%) and clearly no one is suddenly doubling damage with an extra generator. Something must be wrong

**Comment by A2Broslol** [comment]
Nice

**Pull request merged**
