### PR TITLE
Crash problems fixed

### PR DESCRIPTION
**Pull request by tardisfromtornspace**
This should fix the crash problems produced by the rank 23 C-Slot

### CODE REVIEW

**Comment by tardisfromtornspace** [comment]
Could you do a proper restart please? Otherwise the crashes will be happening until tomorrow

**Comment by johnnyapol** [comment]
Every time the server restarts (planed or unplanned like in an crash), it fetches the latest from torn-production. It looks like this change has already been deployed.

**Comment by tardisfromtornspace** [comment]
Alright - in that case, I don't fully get what part of the new C-Slot is making the game crash

**Comment by tardisfromtornspace** [comment]
Ok I think I found one, thanks for spotting the other

**Pull request merged**
