### PR TITLE
EMP Balance Changes

### PR DESCRIPTION
**Pull request by DamienVesper**
**Describe the feature addition / change you have made:**
EMP has been changed much in this PR to reflect the old style of EMP PvP.

**Describe why you have added / changed this feature:**
This has been created to reduce inflation and put more XP in circulation (through the additional risk of an EMP lock while grinding bases, as well as generic PvP. This also allows for more PvP in which a player can actually be killed.

EMP can now:
 - Disable shields.
 - Stop and prevent movement.
 - Prevent use of *all* weapons.

Weapon stats have also changed:
 - EMP Blast: 4s charge / 4s stun
 - EMP Mine: 2s charge / 2.25s stun
 - EMP Missile: 4s charge/ 1s stun

### CODE REVIEW

**Comment by Ann1h1lator** [comment]
This is so dumb, players can fire emp missile three times a second

**Comment by DamienVesper** [comment]
> This is so dumb, players can fire emp missile three times a second

1.5 seconds / missile = 3 missiles / second ???

**Comment by tardisfromtornspace** [comment]
Problem comes from the fact that most players have enough energy to do what anni said. To fix that, either make it so EMP-based weapons cannot charge faster, or get rid of energy altogether.

**Comment by DamienVesper** [comment]
> Problem comes from the fact that most players have enough energy to do what anni said. To fix that, either make it so EMP-based weapons cannot charge faster, or get rid of energy altogether.

That can certainly be arranged.

**Comment by DamienVesper** [comment]
> Also, was nerfing generators intentional?
> With two generatores:
> Before: 1.08* 1.08 = 1.1664
> Now: (2* 0.08) + 1 = 1.16
> Now, with four generators:
> Before: 1.36048896
> Now: 4* 0.08 + 1 = 1.32

Yes, as it wasn't straightforward, and I wanted to tweak it a bit to tone down the abnormally high energy levels players have.

**Pull request closed without merging**
